# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # Standard hooks for general file health
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml # Checks yaml files for parseable syntax.
      - id: end-of-file-fixer # Ensures that a file is either empty, or ends with one newline.
      - id: trailing-whitespace # Trims trailing whitespace.
      - id: check-toml # Checks toml files for parseable syntax.
      - id: check-merge-conflict # Checks for files that contain merge conflict strings.

  # Hooks for Rust code formatting and linting
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: ["--all", "--", "--check"]
      - id: clippy
        # Matches the arguments used in the CI workflow
        args: ["--workspace", "--all-targets", "--", "-D", "warnings"]

  # Hook for checking for unused dependencies in Cargo.toml
  - repo: https://github.com/est31/cargo-udeps
    rev: v0.1.47
    hooks:
      - id: cargo-udeps
        args: ["--all-targets", "--backend=cargo-check"]