// generated by `sqlx migrate build-script`
fn main() {
    // trigger recompilation when a new migration is added
    #[cfg(feature = "db-sqlite")]
    println!("cargo:rerun-if-changed=migrations/sqlite");

    #[cfg(feature = "db-postgres")]
    println!("cargo:rerun-if-changed=migrations/postgres");
}
