[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.9"
tokio = { version = "1", features = ["full", "rt-multi-thread"] }
reqwest = "0.12.9"
chrono = "0.4"
tower-http = { version = "0.6.2", features = ["fs"] }
