[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
slint = { version = "1.12.1", features = ["serde"] }
validator = { version = "0.18.1", features = ["derive"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
sqlx = { version = "0.8.0", default-features = false, features = ["macros", "sqlite"] }

[build-dependencies]
slint-build = "1.12.1"