// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContactDto = { id: number, name: string, email: string, age: number, subscribed: boolean, contactType: string, };

export type Credentials = { email: string, password: string, };

export type LoginResponse = { access_token: string, refresh_token: string, };
