// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContactDto = {
  id: bigint | null;
  name: string;
  email: string;
  age: bigint;
  subscribed: boolean;
  contact_type: string;
};

export type Credentials = { email: string; password: string };

export type LoginResponse = { token: string };
